import { KeyboardMap } from "./types";

export const keyboardMap: KeyboardMap = {
  // row1
  "`": {
    key: "Backquote",
    center_x: 0.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["1"],
    modifiers: [],
  },
  "~": {
    key: "Backquote",
    center_x: 0.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["1"],
    modifiers: ["ShiftLeft"],
  },
  1: {
    key: "Digit1",
    center_x: 1.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["`", "2", "Q"],
    modifiers: [],
  },
  "!": {
    key: "Digit1",
    center_x: 1.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["`", "2", "Q"],
    modifiers: ["ShiftLeft"],
  },
  2: {
    key: "Digit2",
    center_x: 2.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["1", "3", "Q", "W"],
    modifiers: [],
  },
  "@": {
    key: "Digit2",
    center_x: 2.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["1", "3", "Q", "W"],
    modifiers: ["ShiftLeft"],
  },
  3: {
    key: "Digit3",
    center_x: 3.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["2", "4", "W", "E"],
    modifiers: [],
  },
  "#": {
    key: "Digit3",
    center_x: 3.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["2", "4", "W", "E"],
    modifiers: ["ShiftLeft"],
  },
  4: {
    key: "Digit4",
    center_x: 4.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["3", "5", "E", "R"],
    modifiers: [],
  },
  $: {
    key: "Digit4",
    center_x: 4.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["3", "5", "E", "R"],
    modifiers: ["ShiftLeft"],
  },
  5: {
    key: "Digit5",
    center_x: 5.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["4", "6", "R", "T"],
    modifiers: [],
  },
  "%": {
    key: "Digit5",
    center_x: 5.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["4", "6", "R", "T"],
    modifiers: ["ShiftLeft"],
  },
  6: {
    key: "Digit6",
    center_x: 6.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["5", "7", "T", "Y"],
    modifiers: [],
  },
  "^": {
    key: "Digit6",
    center_x: 6.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["5", "7", "T", "Y"],
    modifiers: ["ShiftLeft"],
  },
  7: {
    key: "Digit7",
    center_x: 7.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["6", "8", "Y", "U"],
    modifiers: [],
  },
  "&": {
    key: "Digit7",
    center_x: 7.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["6", "8", "Y", "U"],
    modifiers: ["ShiftLeft"],
  },
  8: {
    key: "Digit8",
    center_x: 8.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["7", "9", "U", "I"],
    modifiers: [],
  },
  "*": {
    key: "Digit8",
    center_x: 8.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["7", "9", "U", "I"],
    modifiers: ["ShiftLeft"],
  },
  9: {
    key: "Digit9",
    center_x: 9.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["8", "0", "I", "O"],
    modifiers: [],
  },
  "(": {
    key: "Digit9",
    center_x: 9.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["8", "0", "I", "O"],
    modifiers: ["ShiftLeft"],
  },
  0: {
    key: "Digit0",
    center_x: 10.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["9", "-", "O", "P"],
    modifiers: [],
  },
  ")": {
    key: "Digit0",
    center_x: 10.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["9", "-", "O", "P"],
    modifiers: ["ShiftLeft"],
  },
  "-": {
    key: "Minus",
    center_x: 11.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["0", "=", "P", "["],
    modifiers: [],
  },
  _: {
    key: "Minus",
    center_x: 11.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["0", "=", "P", "["],
    modifiers: ["ShiftLeft"],
  },
  "=": {
    key: "Equal",
    center_x: 12.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["-", "[", "]"],
    modifiers: [],
  },
  "+": {
    key: "Equal",
    center_x: 12.25,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["-", "[", "]"],
    modifiers: ["ShiftLeft"],
  },
  Backspace: {
    key: "Backspace",
    center_x: 13.5,
    center_y: 0.5,
    w: 2.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },

  // BACKSPACE i ShiftLeft nie przez key resolver

  // row2
  Q: {
    key: "KeyQ",
    center_x: 1.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["1", "2", "W", "A", "S"],
    modifiers: [],
  },
  W: {
    key: "KeyW",
    center_x: 2.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["2", "3", "Q", "E", "A", "S", "D"],
    modifiers: [],
  },
  E: {
    key: "KeyE",
    center_x: 3.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["3", "4", "W", "R", "S", "D", "F"],
    modifiers: [],
  },
  R: {
    key: "KeyR",
    center_x: 4.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["4", "5", "E", "T", "D", "F", "G"],
    modifiers: [],
  },
  T: {
    key: "KeyT",
    center_x: 5.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["5", "6", "R", "Y", "F", "G", "H"],
    modifiers: [],
  },
  Y: {
    key: "KeyY",
    center_x: 6.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["6", "7", "T", "U", "G", "H", "J"],
    modifiers: [],
  },
  U: {
    key: "KeyU",
    center_x: 7.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["7", "8", "Y", "I", "H", "J", "K"],
    modifiers: [],
  },
  I: {
    key: "KeyI",
    center_x: 8.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["8", "9", "U", "O", "J", "K", "L"],
    modifiers: [],
  },
  O: {
    key: "KeyO",
    center_x: 9.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["9", "0", "I", "P", "K", "L", ";"],
    modifiers: [],
  },
  P: {
    key: "KeyP",
    center_x: 10.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["0", "-", "O", "[", "L", ";", "'"],
    modifiers: [],
  },
  "[": {
    key: "BracketLeft",
    center_x: 11.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["-", "=", "P", "]", ";", "'"],
    modifiers: [],
  },
  "{": {
    key: "BracketLeft",
    center_x: 11.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["-", "=", "P", "]", ";", "'"],
    modifiers: ["ShiftLeft"],
  },
  "]": {
    key: "BracketRight",
    center_x: 12.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["=", "[", "\\", "'"],
    modifiers: [],
  },
  "}": {
    key: "BracketRight",
    center_x: 12.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["=", "[", "\\", "'"],
    modifiers: ["ShiftLeft"],
  },
  "\\": {
    key: "Backslash",
    center_x: 13.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["]"],
    modifiers: [],
  },
  "|": {
    key: "Backslash",
    center_x: 13.75,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["]"],
    modifiers: ["ShiftLeft"],
  },

  // row3
  A: {
    key: "KeyA",
    center_x: 2.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["Q", "W", "S", "Z"],
    modifiers: [],
  },
  S: {
    key: "KeyS",
    center_x: 3.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["W", "E", "A", "D", "Z", "X"],
    modifiers: [],
  },
  D: {
    key: "KeyD",
    center_x: 4.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["E", "R", "S", "F", "X", "C"],
    modifiers: [],
  },
  F: {
    key: "KeyF",
    center_x: 5.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["R", "T", "D", "G", "C", "V"],
    modifiers: [],
  },
  G: {
    key: "KeyG",
    center_x: 6.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["T", "Y", "F", "H", "V", "B"],
    modifiers: [],
  },
  H: {
    key: "KeyH",
    center_x: 7.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["Y", "U", "G", "J", "B", "N"],
    modifiers: [],
  },
  J: {
    key: "KeyJ",
    center_x: 8.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["U", "I", "H", "K", "N", "M"],
    modifiers: [],
  },
  K: {
    key: "KeyK",
    center_x: 9.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["I", "O", "J", "L", "M", ","],
    modifiers: [],
  },
  L: {
    key: "KeyL",
    center_x: 10.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["O", "P", "K", ";", ",", "."],
    modifiers: [],
  },
  ";": {
    key: "Semicolon",
    center_x: 11.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["P", "[", "L", "'", ".", "/"],
    modifiers: [],
  },
  ":": {
    key: "Semicolon",
    center_x: 11.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["P", "[", "L", "'", ".", "/"],
    modifiers: ["ShiftLeft"],
  },
  "'": {
    key: "Quote",
    center_x: 12.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["[", "]", ";", "/"],
    modifiers: [],
  },
  '"': {
    key: "Quote",
    center_x: 12.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["[", "]", ";", "/"],
    modifiers: ["ShiftLeft"],
  },

  // row4
  ShiftLeft: {
    key: "ShiftLeft",
    center_x: 1.125,
    center_y: 3.5,
    w: 2.25,
    h: 1.0,
    neighbors: ["A", "Z"],
    modifiers: [],
  },
  Z: {
    key: "KeyZ",
    center_x: 2.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["A", "S", "X"],
    modifiers: [],
  },
  X: {
    key: "KeyX",
    center_x: 3.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["S", "D", "Z", "C"],
    modifiers: [],
  },
  C: {
    key: "KeyC",
    center_x: 4.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["D", "F", "X", "V"],
    modifiers: [],
  },
  V: {
    key: "KeyV",
    center_x: 5.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["F", "G", "C", "B"],
    modifiers: [],
  },
  B: {
    key: "KeyB",
    center_x: 6.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["G", "H", "V", "N"],
    modifiers: [],
  },
  N: {
    key: "KeyN",
    center_x: 7.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["H", "J", "B", "M"],
    modifiers: [],
  },
  M: {
    key: "KeyM",
    center_x: 8.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["J", "K", "N", ","],
    modifiers: [],
  },
  ",": {
    key: "Comma",
    center_x: 9.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["K", "L", "M", "."],
    modifiers: [],
  },
  "<": {
    key: "Comma",
    center_x: 9.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["K", "L", "M", "."],
    modifiers: ["ShiftLeft"],
  },
  ".": {
    key: "Period",
    center_x: 10.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["L", ";", ",", "/"],
    modifiers: [],
  },
  ">": {
    key: "Period",
    center_x: 10.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: ["L", ";", ",", "/"],
    modifiers: ["ShiftLeft"],
  },
  "/": {
    key: "Slash",
    center_x: 11.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: [".", ";", "'"],
    modifiers: [],
  },
  "?": {
    key: "Slash",
    center_x: 11.5,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: [".", ";", "'"],
    modifiers: ["ShiftLeft"],
  },

  // row5
  Space: {
    key: "Space",
    center_x: 7.25,
    center_y: 4.5,
    w: 6.25,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Tab: {
    key: "Tab",
    center_x: 0.75,
    center_y: 1.5,
    w: 1.5,
    h: 1.0,
    neighbors: ["Backquote", "KeyQ"],
    modifiers: [],
  },
  CapsLock: {
    key: "CapsLock",
    center_x: 0.875,
    center_y: 2.5,
    w: 1.75,
    h: 1.0,
    neighbors: ["Tab", "KeyA", "ShiftLeft"],
    modifiers: [],
  },
  ShiftRight: {
    key: "ShiftRight",
    center_x: 12.375,
    center_y: 3.5,
    w: 2.75,
    h: 1.0,
    neighbors: ["Slash"],
    modifiers: [],
  },
  ControlLeft: {
    key: "ControlLeft",
    center_x: 0.75,
    center_y: 4.5,
    w: 1.5,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  MetaLeft: {
    key: "MetaLeft",
    center_x: 2.0,
    center_y: 4.5,
    w: 1.25,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  AltLeft: {
    key: "AltLeft",
    center_x: 3.5,
    center_y: 4.5,
    w: 1.25,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  AltRight: {
    key: "AltRight",
    center_x: 11.0,
    center_y: 4.5,
    w: 1.25,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  MetaRight: {
    key: "MetaRight",
    center_x: 12.5,
    center_y: 4.5,
    w: 1.25,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  ContextMenu: {
    key: "ContextMenu",
    center_x: 13.5,
    center_y: 4.5,
    w: 1.25,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  ControlRight: {
    key: "ControlRight",
    center_x: 14.75,
    center_y: 4.5,
    w: 1.5,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Enter: {
    key: "Enter",
    center_x: 13.125,
    center_y: 2.0,
    w: 2.25,
    h: 2.0,
    neighbors: ["Quote", "BracketRight"],
    modifiers: [],
  },

  // Function keys
  Escape: {
    key: "Escape",
    center_x: 0.5,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F1: {
    key: "F1",
    center_x: 2.0,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F2: {
    key: "F2",
    center_x: 3.0,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F3: {
    key: "F3",
    center_x: 4.0,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F4: {
    key: "F4",
    center_x: 5.0,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F5: {
    key: "F5",
    center_x: 6.5,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F6: {
    key: "F6",
    center_x: 7.5,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F7: {
    key: "F7",
    center_x: 8.5,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F8: {
    key: "F8",
    center_x: 9.5,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F9: {
    key: "F9",
    center_x: 11.0,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F10: {
    key: "F10",
    center_x: 12.0,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F11: {
    key: "F11",
    center_x: 13.0,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  F12: {
    key: "F12",
    center_x: 14.0,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },

  // Arrow keys and navigation cluster
  Insert: {
    key: "Insert",
    center_x: 16.5,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Delete: {
    key: "Delete",
    center_x: 17.5,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Home: {
    key: "Home",
    center_x: 16.5,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  End: {
    key: "End",
    center_x: 17.5,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  PageUp: {
    key: "PageUp",
    center_x: 16.5,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  PageDown: {
    key: "PageDown",
    center_x: 17.5,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  ArrowUp: {
    key: "ArrowUp",
    center_x: 17.0,
    center_y: 4.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  ArrowLeft: {
    key: "ArrowLeft",
    center_x: 16.0,
    center_y: 5.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  ArrowDown: {
    key: "ArrowDown",
    center_x: 17.0,
    center_y: 5.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  ArrowRight: {
    key: "ArrowRight",
    center_x: 18.0,
    center_y: 5.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },

  // Numeric keypad
  NumLock: {
    key: "NumLock",
    center_x: 20.0,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  NumpadDivide: {
    key: "NumpadDivide",
    center_x: 21.0,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  NumpadMultiply: {
    key: "NumpadMultiply",
    center_x: 22.0,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  NumpadSubtract: {
    key: "NumpadSubtract",
    center_x: 23.0,
    center_y: 0.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Numpad7: {
    key: "Numpad7",
    center_x: 20.0,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Numpad8: {
    key: "Numpad8",
    center_x: 21.0,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Numpad9: {
    key: "Numpad9",
    center_x: 22.0,
    center_y: 1.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  NumpadAdd: {
    key: "NumpadAdd",
    center_x: 23.0,
    center_y: 2.0,
    w: 1.0,
    h: 2.0,
    neighbors: [],
    modifiers: [],
  },
  Numpad4: {
    key: "Numpad4",
    center_x: 20.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Numpad5: {
    key: "Numpad5",
    center_x: 21.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Numpad6: {
    key: "Numpad6",
    center_x: 22.0,
    center_y: 2.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Numpad1: {
    key: "Numpad1",
    center_x: 20.0,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Numpad2: {
    key: "Numpad2",
    center_x: 21.0,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Numpad3: {
    key: "Numpad3",
    center_x: 22.0,
    center_y: 3.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  NumpadEnter: {
    key: "NumpadEnter",
    center_x: 23.0,
    center_y: 4.0,
    w: 1.0,
    h: 2.0,
    neighbors: [],
    modifiers: [],
  },
  Numpad0: {
    key: "Numpad0",
    center_x: 20.5,
    center_y: 4.5,
    w: 2.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  NumpadDecimal: {
    key: "NumpadDecimal",
    center_x: 22.0,
    center_y: 4.5,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },

  // Print screen, scroll lock, pause
  PrintScreen: {
    key: "PrintScreen",
    center_x: 15.5,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  ScrollLock: {
    key: "ScrollLock",
    center_x: 16.5,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
  Pause: {
    key: "Pause",
    center_x: 17.5,
    center_y: -1.0,
    w: 1.0,
    h: 1.0,
    neighbors: [],
    modifiers: [],
  },
};
